win_installer: try fix build error by updating the system
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.3.0-2' required by mingw-w64-i686-gcc-ada
:: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.3.0-2' required by mingw-w64-i686-gcc-objc
:: removing mingw-w64-i686-termcap breaks dependency 'mingw-w64-i686-termcap' required by mingw-w64-i686-readline
:: removing mingw-w64-i686-ncurses breaks dependency 'mingw-w64-i686-ncurses' required by mingw-w64-i686-sqlite3